name: pcrglobwb_python3
channels:
  - conda-forge
dependencies:
  - python=3.7        # or =3.11, depending on what you target
  - numpy<2
  - netcdf4>=1.5.3
  - pcraster==4.3.0
  - python-dateutil
  - six
  - zlib
  - pip
  - pip:
      - grpc4bmi==0.4.0
      - cython

#   name: pcrglobwb_python3

# channels:
#   - conda-forge
# dependencies:
#   - python>=3.10
#   - numpy
#   - pip
#   - python-dateutil
#   - six  
#   - zlib
#   - pcraster>=4.4.0
#   - pip:
#     - netcdf4>=1.5.3
#   - cdo
#   - nco
#   - ncview
  
# Note: You may want to exclude cdo, nco, and ncview.

